--PostgresSQL create script

-- DROP DATABASE IF EXISTS "AI_POC";

CREATE DATABASE "AI_POC"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

DROP ROLE IF EXISTS ai_poc_usr;
CREATE ROLE ai_poc_usr WITH LOGIN PASSWORD 'ai_poc_pwd';
GRANT ALL PRIVILEGES ON DATABASE "AI_POC" TO ai_poc_usr;
GRANT USAGE ON SCHEMA public to ai_poc_usr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ai_poc_usr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ai_poc_usr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ai_poc_usr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ai_poc_usr;

-- database must be configred as vestor store
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS vector_store (
	id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	content text,
	metadata json,
	embedding vector(768)
);
-- 1536 is the default embedding dimension
-- ALTER TABLE vector_store DROP COLUMN embedding;
-- ALTER TABLE vector_store ADD COLUMN embedding vector(768);

CREATE INDEX ON vector_store USING HNSW (embedding vector_cosine_ops);	

DROP TABLE IF EXISTS TRANSMISSION_STATUS_HIST;
DROP TABLE IF EXISTS TRANSMISSION_STATUS;
DROP TABLE IF EXISTS TRANSMISSION_ERROR;

-- Tables for Transmissions
CREATE TABLE IF NOT EXISTS TRANSMISSION_STATUS(
	TRANSMISSION_STATUS_ID SERIAL NOT NULL UNIQUE,
	RECEIPT_ID VARCHAR(32) NOT NULL UNIQUE,
	STATUS VARCHAR(100) NOT NULL,
	FORM_TYPE VARCHAR(100) NOT NULL,
	SERVER VARCHAR(100) NOT NULL,
	INSERTED_DT TIMESTAMP NOT NULL,
	UPDATE_DT TIMESTAMP NOT NULL,
	PRIMARY KEY (TRANSMISSION_STATUS_ID)
);

CREATE TABLE IF NOT EXISTS TRANSMISSION_STATUS_HIST(
	TRANSMISSION_STATUS_HIST_ID SERIAL NOT NULL UNIQUE,
	TRANSMISSION_STATUS_ID SERIAL NOT NULL,
	RECEIPT_ID VARCHAR(32) NOT NULL,
	STATUS VARCHAR(100),
	INSERTED_DT TIMESTAMP NOT NULL,
	PRIMARY KEY (TRANSMISSION_STATUS_HIST_ID),
	FOREIGN KEY (TRANSMISSION_STATUS_ID) REFERENCES TRANSMISSION_STATUS (TRANSMISSION_STATUS_ID)
);

CREATE TABLE IF NOT EXISTS TRANSMISSION_ERROR(
	TRANSMISSION_ERROR_ID SERIAL NOT NULL UNIQUE,
	RECEIPT_ID VARCHAR(32) NOT NULL,
	ERROR_CD VARCHAR(100) NOT NULL,
	ERROR_MSG VARCHAR(4000) NOT NULL,
	ERROR_LEVEL VARCHAR(100) NOT NULL,
	LINE_NUM VARCHAR(100),
  XPATH_MAPPING VARCHAR(1000),
	ADDITIONAL_INFO VARCHAR(2000),
	PRIMARY KEY (TRANSMISSION_ERROR_ID)
);
