SELECT f.PROCESSED_IND,
	f.COMPLETED_IND,
	a.DOC_SEQUENCE_NUM,
	a.ATTCH_BYTE_SIZE_NUM,
	A.BATCH_ID, 
	B.STATUS,
	A.GSO_ID,
	x.TAX_YR, 
	B.CREATE_DT, 
	C.errortype, 
	c.errormsg,
	d.ERROR_CD, 
	d.ERROR_MSG_TXT, 
	e.error_message_cd, 
	e.error_message_txt, 
	A.EXCHANGEID_NUM
FROM transmission_1095A a 
	FULL OUTER JOIN IFS_STATUS b ON A.GSO_ID = B.GSO_ID 
	FULL OUTER JOIN IFS_ERROR c ON B.GSO_ID = C.GSO_ID 
	FULL OUTER JOIN transmission_error d ON C.GSO_ID = d.GSO_ID
	FULL OUTER JOIN TRANSMISSION_1095_EXT x ON a.GSO_ID = x.GSO_ID 
	FULL OUTER JOIN TIN_VALIDATION_ERROR e ON B.GSO_ID = E.GSO_ID
	FULL OUTER JOIN bulk_tin f ON B.GSO_ID = f.GSO_ID
WHERE A.batch_id = '2023-02-16T00:00:06Z'
	AND C.ERRORTYPE NOT LIKE 'E0%' 
	--AND C. ERRORTYPE NOT like 'Schema Validation Error'
--ORDER BY a.GSO_ID desc;
ORDER BY a.DOC_SEQUENCE_NUM; 