server:
  port: 8089

spring:
  profiles:
    active: default
  application:
    name: countycfxwebsvc
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/counties
    username: counties_user
    password: counties_pwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true  
    open-in-view: false
    
logging:
  #level.root: debug
  file: countycfxwebsvc.log

cxf:
  path: /ws/*

ws:
 namespace.uri: http://www.tier3llc.com/countyservice
 
context.path: com.tier3llc.countyservice
  
workingdir:
  path: 'C:\Users\Anthony\Documents\My Git\Spring-Boot-Projects\CountyCfxWebService-WorkingDir\'
  
---

spring:
  config:
    activate:
      on-profile: laptop
  
workingdir:
  path: 'C:\Users\Anthony\Documents\My Documents\My Git\Spring-Boot-Projects\CountyCfxWebService-WorkingDir\'        