package us.states.cucumber.steps;

/**
 * @author Anthony Hemmans
 * @date Jun 22, 2022
 *
 */
public enum ApiMethod {

	DELETE_APPOINTMENT,
	DELETE_TIMESLOT,
	GET_APPOINTMENT,
	GET_APPOINTMENT_BY_APPOINTMENT_ID,
	GET_APPOINTMENT_BY_CONFIRMATION_NUMBER,
	GET_APPOINTMENT_BY_OTP,
	GET_AVAILABLE_APPOINTMENTS,
	GET_TIMESLOTS,
	GET_CUSTOMER,
	GET_OFFICES,
	GET_OFFICE_CLOSURES,
	GET_ONE_TIME_PASS_CODE,
	GET_REFERENCE_DATA,
	POST_APPOINTMENT,
	POST_CUSTOMER,
	POST_TIMESLOT,
	PUT_APPOINTMENT,
	PUT_TIMESLOT
	
}


